// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PratikSurvivor.Contexts;

#nullable disable

namespace PratikSurvivor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PratikSurvivor.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7733),
                            IsDeleted = false,
                            Name = "Ünlüler"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7745),
                            IsDeleted = false,
                            Name = "Gönüllüler"
                        });
                });

            modelBuilder.Entity("PratikSurvivor.Models.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Competitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7835),
                            FirstName = "Acun",
                            IsDeleted = false,
                            LastName = "Ilıcalı"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7837),
                            FirstName = "Aleyna",
                            IsDeleted = false,
                            LastName = "Avcı"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7838),
                            FirstName = "Hadise",
                            IsDeleted = false,
                            LastName = "Açıkgöz"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7839),
                            FirstName = "Sertan",
                            IsDeleted = false,
                            LastName = "Bozkuş"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7839),
                            FirstName = "Özge",
                            IsDeleted = false,
                            LastName = "Açık"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7840),
                            FirstName = "Kıvanç",
                            IsDeleted = false,
                            LastName = "Tatlıtuğ"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7841),
                            FirstName = "Ahmet",
                            IsDeleted = false,
                            LastName = "Yılmaz"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7842),
                            FirstName = "Elif",
                            IsDeleted = false,
                            LastName = "Demirtaş"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7842),
                            FirstName = "Cem",
                            IsDeleted = false,
                            LastName = "Öztürk"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 3, 22, 17, 37, 21, 349, DateTimeKind.Local).AddTicks(7843),
                            FirstName = "Ayşe",
                            IsDeleted = false,
                            LastName = "Karaca"
                        });
                });

            modelBuilder.Entity("PratikSurvivor.Models.Competitor", b =>
                {
                    b.HasOne("PratikSurvivor.Models.Category", "Category")
                        .WithMany("Competitors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PratikSurvivor.Models.Category", b =>
                {
                    b.Navigation("Competitors");
                });
#pragma warning restore 612, 618
        }
    }
}
